### ISSUE TITLE
location of file

### ISSUE THREAD

**Issue by whoarethebritons** [whoarethebritons/WiFile#5]
I believe you said res/menus/raws

but does that folder exist before you output?

**Comment by karenTran510** [comment]
Uhh at first no, you have to create the /raw folder within the /res. The entire pathname is supposed to be "main/res/raw/filehistory". 
"filehistory" is the text file that will store all files that needs to be transferred.

**Comment by whoarethebritons** [comment]
so main/res/raw/filehistory.txt

**Comment by karenTran510** [comment]
Yup that's right

**Comment by whoarethebritons** [comment]
okay cool

On Tue, Oct 21, 2014 at 8:11 PM, karenTran510 notifications@github.com
wrote:

> Yup that's right
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/whoarethebritons/WiFile/issues/5#issuecomment-60030915
> .

## 

Alfred Hitchcock  - "Television has brought back murder into the home -
where it belongs."

**Comment by whoarethebritons** [comment]
but that's just where we're storing it and not the location on the sd card for the phone

**Comment by whoarethebritons** [comment]
shouldn't it be something like this

http://developer.android.com/guide/topics/data/data-storage.html#filesInternal

**Comment by whoarethebritons** [comment]
"Tip: If you want to save a static file in your application at compile time, save the file in your project res/raw/ directory. You can open it with openRawResource(), passing the R.raw.<filename> resource ID. This method returns an InputStream that you can use to read the file (but you cannot write to the original file)."
